import { BusStop, BusRoute, VehiclePosition } from '../types/index.js';

class DatabaseStore {
  private stops: BusStop[] = [];
  private routes: BusRoute[] = [];
  private vehicles: VehiclePosition[] = [];

  constructor() {
    this.seedStops();
    this.seedRoutes();
    this.seedVehicles();
  }

  private seedStops() {
    this.stops = [
      {
        id: 'stop_broadway',
        name: 'Broadway Bus Terminus',
        nameTamil: 'பிராட்வே பேருந்து நிலையம்',
        lat: 13.0878,
        lng: 80.2835,
        area: 'Broadway',
        district: 'Chennai',
        landmarks: ['Parrys Corner', 'High Court'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['1', '101', '18A', '21', '21C', '21L', '21X', '221', '26', '26B', '26G', '26K', '26M', '26R', '29A', '2A', '2B', '4', '50', '60A', '88KET', '88R', '8B'],
        popularity: 99
      },
      {
        id: 'stop_island_ground',
        name: 'Island Ground / Anna Square',
        nameTamil: 'தீவு திடல் / அண்ணா சதுக்கம்',
        lat: 13.0722,
        lng: 80.28,
        area: 'Triplicane',
        district: 'Chennai',
        landmarks: ['Marina Beach', 'Fort St. George'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['1', '102', '102C', '102K', '102P', '102S', '102X', '109', '13', '15', '21', '21C', '21E', '21G', '21L', '21X', '22', '242', '24A', '25', '27B', '29A', '2A', '4', '40A', '40H', '44', '45B', '45E', '8B'],
        popularity: 97
      },
      {
        id: 'stop_royapuram',
        name: 'Royapuram Bus Stand',
        nameTamil: 'ராயபுரம் பேருந்து நிலையம்',
        lat: 13.1112,
        lng: 80.2925,
        area: 'Royapuram',
        district: 'Chennai',
        landmarks: ['Royapuram Railway Station'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['120', '150', '188C', '18A', '26', '26B', '26G', '26K', '26M', '26R', '50', '54', '60A'],
        popularity: 93
      },
      {
        id: 'stop_thiruvanmiyur',
        name: 'Thiruvanmiyur Bus Depot',
        nameTamil: 'திருவான்மியூர்',
        lat: 12.983,
        lng: 80.2594,
        area: 'Thiruvanmiyur',
        district: 'Chennai',
        landmarks: ['Marundeeswarar Temple', 'Tidel Park'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['1', '102A', '102CT', '3', '588', '78', '91'],
        popularity: 96
      },
      {
        id: 'stop_t_nagar_terminus',
        name: 'T. Nagar Bus Terminus',
        nameTamil: 'தி. நகர் பேருந்து நிலையம்',
        lat: 13.0418,
        lng: 80.2341,
        area: 'T. Nagar',
        district: 'Chennai',
        landmarks: ['Ranganathan Street', 'Panagal Park'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['13', '154', '19', '19A', '19B', '19C', '19D', '19T', '23C', '3', '47T', '49A', '597', '72', 'M27'],
        popularity: 99
      },
      {
        id: 'stop_kannadasan_nagar',
        name: 'K. Kannadasan Nagar',
        nameTamil: 'க. கண்ணதாசன் நகர்',
        lat: 13.1345,
        lng: 80.2465,
        area: 'Vyasarpadi',
        district: 'Chennai',
        landmarks: ['Vyasarpadi Industrial Estate'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['170TX', '2A', '2B'],
        popularity: 88
      },
      {
        id: 'stop_kilambakkam',
        name: 'Kalaignar Centenary Bus Terminus (KCBT Kilambakkam)',
        nameTamil: 'கிளம்பாக்கம் பேருந்து நிலையம்',
        lat: 12.8342,
        lng: 80.0768,
        area: 'Kilambakkam',
        district: 'Chengalpattu',
        landmarks: ['Vandalur Flyover', 'KCBT Terminal'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['104A', '104C', '104F', '104M', '104T', '170TX', '18A', '206', '21G', '297', '91'],
        popularity: 100
      },
      {
        id: 'stop_thiruporur',
        name: 'Thiruporur Bus Stand',
        nameTamil: 'திருப்போரூர்',
        lat: 12.7245,
        lng: 80.1912,
        area: 'Thiruporur',
        district: 'Chengalpattu',
        landmarks: ['Kandaswamy Temple'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['102', '102X', '19', '19B', '221'],
        popularity: 91
      },
      {
        id: 'stop_siruseri',
        name: 'Siruseri IT Park',
        nameTamil: 'சிறுசேரி தகவல் தொழில்நுட்ப பூங்கா',
        lat: 12.8285,
        lng: 80.2185,
        area: 'Siruseri',
        district: 'Chengalpattu',
        landmarks: ['SIPCOT IT Park', 'TCS Campus'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['102', '102CT', '102S', '19', '19A', '19B', '19C', '19D', '19T', '570'],
        popularity: 94
      },
      {
        id: 'stop_ennore',
        name: 'Ennore Bus Stand',
        nameTamil: 'எண்ணூர்',
        lat: 13.2145,
        lng: 80.321,
        area: 'Ennore',
        district: 'Chennai',
        landmarks: ['Ennore Thermal Power Station'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['4'],
        popularity: 85
      },
      {
        id: 'stop_thiruvika_nagar',
        name: 'Thiru.Vi.Ka. Nagar',
        nameTamil: 'திரு.வி.க. நகர்',
        lat: 13.1154,
        lng: 80.2356,
        area: 'Perambur',
        district: 'Chennai',
        landmarks: ['Agasthya Theatre'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['104T', '170C', '8B'],
        popularity: 89
      },
      {
        id: 'stop_cmbt',
        name: 'CMBT Koyambedu Bus Terminus',
        nameTamil: 'கோயம்பேடு பேருந்து நிலையம்',
        lat: 13.0694,
        lng: 80.1948,
        area: 'Koyambedu',
        district: 'Chennai',
        landmarks: ['CMBT Metro Station', 'Vegetable Market'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['104C', '104CX', '114', '121', '15', '153', '170TX', '27B', '570', '77', '78', '85', 'M27'],
        popularity: 98
      },
      {
        id: 'stop_besant_nagar',
        name: 'Besant Nagar Bus Depot',
        nameTamil: 'பெசன்ட் நகர்',
        lat: 13.0003,
        lng: 80.2667,
        area: 'Besant Nagar',
        district: 'Chennai',
        landmarks: ["Elliot's Beach"],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['23C', '29C'],
        popularity: 95
      },
      {
        id: 'stop_ayanavaram',
        name: 'Ayanavaram Bus Depot',
        nameTamil: 'அயனாவரம்',
        lat: 13.0985,
        lng: 80.2385,
        area: 'Ayanavaram',
        district: 'Chennai',
        landmarks: ['Mental Health Hospital'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['23C'],
        popularity: 90
      },
      {
        id: 'stop_perambur',
        name: 'Perambur Bus Stand',
        nameTamil: 'பெரம்பூர்',
        lat: 13.1095,
        lng: 80.2485,
        area: 'Perambur',
        district: 'Chennai',
        landmarks: ['Perambur Railway Station', 'Spectrum Mall'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['142', '29A', '29C'],
        popularity: 92
      },
      {
        id: 'stop_poonamallee',
        name: 'Poonamallee Bus Terminus',
        nameTamil: 'பூவிருந்தவல்லி',
        lat: 13.0485,
        lng: 80.0912,
        area: 'Poonamallee',
        district: 'Tiruvallur',
        landmarks: ['Blind School Signal'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['101', '153', '154', '25', '37', '49A', '54', '578', '591', '66', '66J'],
        popularity: 96
      },
      {
        id: 'stop_iyyappanthangal',
        name: 'Iyyappanthangal Bus Depot',
        nameTamil: 'அய்யப்பன்தாங்கல்',
        lat: 13.0385,
        lng: 80.1385,
        area: 'Iyyappanthangal',
        district: 'Kanchipuram',
        landmarks: ['SRMC Hospital'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['166', '26', '26G', '26K', '49A'],
        popularity: 94
      },
      {
        id: 'stop_ambattur_ie',
        name: 'Ambattur Industrial Estate',
        nameTamil: 'அம்பத்தூர் தொழிற்பேட்டை',
        lat: 13.1012,
        lng: 80.1612,
        area: 'Ambattur',
        district: 'Chennai',
        landmarks: ['TI Cycles'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['34'],
        popularity: 91
      },
      {
        id: 'stop_thiruvotriyur',
        name: 'Thiruvotriyur Bus Stand',
        nameTamil: 'திருவொற்றியூர்',
        lat: 13.1612,
        lng: 80.3012,
        area: 'Thiruvotriyur',
        district: 'Chennai',
        landmarks: ['Thyagaraja Swamy Temple'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['101', '34'],
        popularity: 90
      },
      {
        id: 'stop_pattabiram',
        name: 'Pattabiram Bus Stop',
        nameTamil: 'பட்டாபிராம்',
        lat: 13.1245,
        lng: 80.0612,
        area: 'Pattabiram',
        district: 'Tiruvallur',
        landmarks: ['Hindu College', 'Pattabiram Railway Station'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['40A', '40H'],
        popularity: 87
      },
      {
        id: 'stop_kundrathur',
        name: 'Kundrathur Bus Stand',
        nameTamil: 'குன்றத்தூர் பேருந்து நிலையம்',
        lat: 12.9978,
        lng: 80.0972,
        area: 'Kundrathur',
        district: 'Kanchipuram',
        landmarks: ['Kundrathur Murugan Temple'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['188C', '60A', '66', '66A', '85', '88K', '88KET', '88M', '88R', '89T', 'M88'],
        popularity: 92
      },
      {
        id: 'stop_mangadu',
        name: 'Mangadu Bus Stop',
        nameTamil: 'மாங்காடு',
        lat: 13.0112,
        lng: 80.1154,
        area: 'Mangadu',
        district: 'Kanchipuram',
        landmarks: ['Mangadu Kamakshi Amman Temple'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['26B', '88K'],
        popularity: 88
      },
      {
        id: 'stop_porur',
        name: 'Porur Junction',
        nameTamil: 'போரூர் சந்திப்பு',
        lat: 13.0335,
        lng: 80.1582,
        area: 'Porur',
        district: 'Chennai',
        landmarks: ['Ramachandra Hospital', 'Porur Lake'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['154', '25', '26B', '26M', '26R', '37', '54', '85', '88K', 'S27'],
        popularity: 95
      },
      {
        id: 'stop_ramapuram',
        name: 'Ramapuram Bus Stop',
        nameTamil: 'ராமாபுரம்',
        lat: 13.0385,
        lng: 80.1785,
        area: 'Ramapuram',
        district: 'Chennai',
        landmarks: ['SRM University', 'MGR Gardens'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['188C', '21E', '88K'],
        popularity: 87
      },
      {
        id: 'stop_valasaravakkam',
        name: 'Valasaravakkam Bus Stop',
        nameTamil: 'வலசரவாக்கம்',
        lat: 13.0425,
        lng: 80.1885,
        area: 'Valasaravakkam',
        district: 'Chennai',
        landmarks: ['Police Station'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['25', '88K'],
        popularity: 89
      },
      {
        id: 'stop_vadapalani',
        name: 'Vadapalani Bus Depot',
        nameTamil: 'வடபழனி பேருந்து நிலையம்',
        lat: 13.05,
        lng: 80.2121,
        area: 'Vadapalani',
        district: 'Chennai',
        landmarks: ['Vadapalani Murugan Temple', 'Forum Vijaya Mall'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['27B', '37', '570', '88K', '88M', 'M27', 'M88'],
        popularity: 96
      },
      {
        id: 'stop_ashok_pillar',
        name: 'Ashok Pillar Bus Stop',
        nameTamil: 'அசோக் தூண்',
        lat: 13.0352,
        lng: 80.2123,
        area: 'Ashok Nagar',
        district: 'Chennai',
        landmarks: ['Ashok Nagar Metro', 'Udayam Theatre'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['570', '88K'],
        popularity: 90
      },
      {
        id: 'stop_power_house',
        name: 'Power House Bus Stop',
        nameTamil: 'பவர் ஹவுஸ்',
        lat: 13.0482,
        lng: 80.2175,
        area: 'Kodambakkam',
        district: 'Chennai',
        landmarks: ['TNEB Substation'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['27B', '570', '88K'],
        popularity: 88
      },
      {
        id: 'stop_kodambakkam_rs',
        name: 'Kodambakkam Railway Station',
        nameTamil: 'கோடம்பாக்கம் ரயில் நிலையம்',
        lat: 13.0518,
        lng: 80.2268,
        area: 'Kodambakkam',
        district: 'Chennai',
        landmarks: ['Suburban Railway Station'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['88K'],
        popularity: 92
      },
      {
        id: 'stop_kodambakkam',
        name: 'Kodambakkam Bus Stop',
        nameTamil: 'கோடம்பாக்கம்',
        lat: 13.0514,
        lng: 80.2245,
        area: 'Kodambakkam',
        district: 'Chennai',
        landmarks: ['Kodambakkam Flyover', 'Meenakshi College'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['23C', '25', '26', '27B', '88K'],
        popularity: 94
      },
      {
        id: 'stop_valluvar_kottam',
        name: 'Valluvar Kottam Junction',
        nameTamil: 'வள்ளுவர் கோட்டம்',
        lat: 13.0583,
        lng: 80.2415,
        area: 'Nungambakkam',
        district: 'Chennai',
        landmarks: ['Valluvar Kottam Memorial'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['23C', '27B'],
        popularity: 93
      },
      {
        id: 'stop_guindy',
        name: 'Guindy TVK Estate / Metro',
        nameTamil: 'கிண்டி',
        lat: 13.0067,
        lng: 80.202,
        area: 'Guindy',
        district: 'Chennai',
        landmarks: ['Guindy Metro', 'Race Course', 'IIT Gate'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['154', '170C', '18A', '21E', '21G', '21X', '23V', '45A', '45B', '45E', '570', '60A', '78', 'S27'],
        popularity: 97
      },
      {
        id: 'stop_tambaram_west',
        name: 'Tambaram West Bus Stand',
        nameTamil: 'தாம்பரம் மேற்கு',
        lat: 12.925,
        lng: 80.1171,
        area: 'Tambaram',
        district: 'Chennai',
        landmarks: ['Tambaram Railway Station'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['104', '111', '118', '166', '18A', '202', '21G', '266', '31G', '500', '66', '66J', '89T', '96', '99'],
        popularity: 98
      },
      {
        id: 'stop_marina_beach',
        name: 'Marina Beach Light House',
        nameTamil: 'மெரினா கலங்கரை விளக்கம்',
        lat: 13.0398,
        lng: 80.2782,
        area: 'Marina',
        district: 'Chennai',
        landmarks: ['Marina Light House'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['1', '109', '45B'],
        popularity: 96
      },
      {
        id: 'stop_mandaveli',
        name: 'Mandaveli Bus Stand',
        nameTamil: 'மந்தவெளி',
        lat: 13.028,
        lng: 80.26,
        area: 'Mandaveli',
        district: 'Chennai',
        landmarks: ['Mandaveli Railway Station'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['21'],
        popularity: 88
      },
      {
        id: 'stop_kannagi_nagar',
        name: 'Kannagi Nagar SCB',
        nameTamil: 'கண்ணகி நகர்',
        lat: 12.935,
        lng: 80.23,
        area: 'Kannagi Nagar',
        district: 'Chennai',
        landmarks: ['SCB Tenements'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['102K', '21C'],
        popularity: 85
      },
      {
        id: 'stop_velachery',
        name: 'Velachery Bus Terminus',
        nameTamil: 'வேளச்சேரி',
        lat: 12.978,
        lng: 80.222,
        area: 'Velachery',
        district: 'Chennai',
        landmarks: ['Velachery Railway Station', 'Phoenix Marketcity'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['21L', '23V', '3'],
        popularity: 94
      },
      {
        id: 'stop_korattur',
        name: 'Korattur / Villivakkam Bus Stand',
        nameTamil: 'கொரட்டூர்',
        lat: 13.11,
        lng: 80.19,
        area: 'Korattur',
        district: 'Chennai',
        landmarks: ['Korattur Railway Station'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['22', '23V'],
        popularity: 86
      },
      {
        id: 'stop_vivekananda_house',
        name: 'Vivekananda House (Ice House)',
        nameTamil: 'விவேகானந்தர் இல்லம்',
        lat: 13.053,
        lng: 80.28,
        area: 'Triplicane',
        district: 'Chennai',
        landmarks: ['Vivekananda Cultural Centre'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['24A', '32A', '32B', '45A'],
        popularity: 90
      },
      {
        id: 'stop_anna_nagar_west',
        name: 'Anna Nagar West Bus Depot',
        nameTamil: 'அண்ணா நகர் மேற்கு',
        lat: 13.088,
        lng: 80.208,
        area: 'Anna Nagar',
        district: 'Chennai',
        landmarks: ['Anna Nagar Tower Park'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['24A'],
        popularity: 93
      },
      {
        id: 'stop_tondiarpet',
        name: 'Tondiarpet Bus Depot',
        nameTamil: 'தண்டையார்பேட்டை',
        lat: 13.128,
        lng: 80.288,
        area: 'Tondiarpet',
        district: 'Chennai',
        landmarks: ['Apollo Hospital Tondiarpet'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['32A'],
        popularity: 88
      },
      {
        id: 'stop_korukkupet',
        name: 'Korukkupet Railway Station',
        nameTamil: 'கொருக்குப்பேட்டை',
        lat: 13.118,
        lng: 80.278,
        area: 'Korukkupet',
        district: 'Chennai',
        landmarks: ['Railway Junction'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['32B'],
        popularity: 86
      },
      {
        id: 'stop_vallalar_nagar',
        name: 'Vallalar Nagar (Mint) Bus Stand',
        nameTamil: 'வள்ளலார் நகர்',
        lat: 13.105,
        lng: 80.282,
        area: 'Mint',
        district: 'Chennai',
        landmarks: ['Stanley Hospital'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['32A', '32B', '37', '44', '57'],
        popularity: 92
      },
      {
        id: 'stop_medavakkam_rd',
        name: 'Medavakkam Road Junction',
        nameTamil: 'மேடவாக்கம்',
        lat: 12.918,
        lng: 80.192,
        area: 'Medavakkam',
        district: 'Chennai',
        landmarks: ['Medavakkam Junction'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['31G'],
        popularity: 87
      },
      {
        id: 'stop_manali',
        name: 'Manali Bus Stand',
        nameTamil: 'மணலி',
        lat: 13.168,
        lng: 80.262,
        area: 'Manali',
        district: 'Chennai',
        landmarks: ['CPCL Refinery'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['44'],
        popularity: 85
      },
      {
        id: 'stop_madipakkam',
        name: 'Madipakkam Bus Stand',
        nameTamil: 'மடிப்பாக்கம்',
        lat: 12.965,
        lng: 80.198,
        area: 'Madipakkam',
        district: 'Chennai',
        landmarks: ['Madipakkam Koot Road'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['45A'],
        popularity: 88
      },
      {
        id: 'stop_kilkattalai',
        name: 'Kilkattalai Bus Stand',
        nameTamil: 'கீழ்க்கட்டளை',
        lat: 12.955,
        lng: 80.188,
        area: 'Kilkattalai',
        district: 'Chennai',
        landmarks: ['Signal Junction'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['45E'],
        popularity: 87
      },
      {
        id: 'stop_icf',
        name: 'ICF / Villivakkam',
        nameTamil: 'ஐ.சி.எஃப்',
        lat: 13.098,
        lng: 80.218,
        area: 'Villivakkam',
        district: 'Chennai',
        landmarks: ['Integral Coach Factory'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['23V', '47T'],
        popularity: 90
      },
      {
        id: 'stop_thiruverkadu',
        name: 'Thiruverkadu Bus Stand',
        nameTamil: 'திருவேற்காடு',
        lat: 13.072,
        lng: 80.122,
        area: 'Thiruverkadu',
        district: 'Tiruvallur',
        landmarks: ['Devi Karumariamman Temple'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['111', '50', '72'],
        popularity: 89
      },
      {
        id: 'stop_redhills',
        name: 'Redhills Bus Terminus',
        nameTamil: 'ரெட்ஹில்ஸ்',
        lat: 13.198,
        lng: 80.198,
        area: 'Redhills',
        district: 'Tiruvallur',
        landmarks: ['Redhills Lake'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['104', '114', '242', '57'],
        popularity: 91
      },
      {
        id: 'stop_hasthinapuram',
        name: 'Hasthinapuram Bus Stand',
        nameTamil: 'ஹஸ்தினாபுரம்',
        lat: 12.945,
        lng: 80.145,
        area: 'Hasthinapuram',
        district: 'Chennai',
        landmarks: ['Hasthinapuram Market'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['66A'],
        popularity: 85
      },
      {
        id: 'stop_avadi',
        name: 'Avadi Bus Terminus',
        nameTamil: 'ஆவடி',
        lat: 13.115,
        lng: 80.1,
        area: 'Avadi',
        district: 'Tiruvallur',
        landmarks: ['Avadi Railway Station', 'HVF Factory'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['104A', '120', '150', '202', '206', '266', '580', '77'],
        popularity: 95
      },
      {
        id: 'stop_nallur',
        name: 'Nallur Bus Stop',
        nameTamil: 'நல்லூர்',
        lat: 12.98,
        lng: 80.06,
        area: 'Nallur',
        district: 'Kanchipuram',
        landmarks: ['Nallur Village'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['88KET'],
        popularity: 80
      },
      {
        id: 'stop_somangalam',
        name: 'Somangalam Bus Stop',
        nameTamil: 'சோமங்கலம்',
        lat: 12.96,
        lng: 80.04,
        area: 'Somangalam',
        district: 'Kanchipuram',
        landmarks: ['Somangalam Temple'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['88M'],
        popularity: 80
      },
      {
        id: 'stop_amarambedu',
        name: 'Amarambedu Bus Stop',
        nameTamil: 'அமரம்பேடு',
        lat: 12.95,
        lng: 80.03,
        area: 'Amarambedu',
        district: 'Kanchipuram',
        landmarks: ['Village Junction'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['88R'],
        popularity: 80
      },
      {
        id: 'stop_adyar',
        name: 'Adyar Bus Depot',
        nameTamil: 'அடையாறு',
        lat: 13.006,
        lng: 80.257,
        area: 'Adyar',
        district: 'Chennai',
        landmarks: ['Adyar Signal', 'Cancer Institute'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['102M', '96', '99'],
        popularity: 95
      },
      {
        id: 'stop_kelambakkam',
        name: 'Kelambakkam Bus Stand',
        nameTamil: 'கேளம்பாக்கம்',
        lat: 12.785,
        lng: 80.222,
        area: 'Kelambakkam',
        district: 'Chengalpattu',
        landmarks: ['OMR Junction'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['102M', '19T'],
        popularity: 92
      },
      {
        id: 'stop_pudupakkam',
        name: 'Pudupakkam Junction',
        nameTamil: 'புதுப்பாக்கம்',
        lat: 12.805,
        lng: 80.208,
        area: 'Pudupakkam',
        district: 'Chengalpattu',
        landmarks: ['Vandalur Road'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['102A'],
        popularity: 84
      },
      {
        id: 'stop_semmancheri',
        name: 'Semmancheri SCB',
        nameTamil: 'செம்மஞ்சேரி',
        lat: 12.868,
        lng: 80.225,
        area: 'Semmancheri',
        district: 'Chennai',
        landmarks: ['Sathyabama University'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['102C'],
        popularity: 88
      },
      {
        id: 'stop_perumbakkam',
        name: 'Perumbakkam SCB',
        nameTamil: 'பெரும்பாக்கம்',
        lat: 12.895,
        lng: 80.195,
        area: 'Perumbakkam',
        district: 'Chennai',
        landmarks: ['Global Hospital'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['102P'],
        popularity: 89
      },
      {
        id: 'stop_kovalam',
        name: 'Kovalam Bus Stand',
        nameTamil: 'கோவளம்',
        lat: 12.79,
        lng: 80.25,
        area: 'Kovalam',
        district: 'Chengalpattu',
        landmarks: ['Kovalam Beach'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['109', '19D'],
        popularity: 88
      },
      {
        id: 'stop_maraimalai_nagar',
        name: 'Maraimalai Nagar IE',
        nameTamil: 'மறைமலை நகர்',
        lat: 12.795,
        lng: 80.025,
        area: 'Maraimalai Nagar',
        district: 'Chengalpattu',
        landmarks: ['Industrial Estate'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['118'],
        popularity: 87
      },
      {
        id: 'stop_minjur',
        name: 'Minjur Bus Stand',
        nameTamil: 'மீஞ்சூர்',
        lat: 13.28,
        lng: 80.26,
        area: 'Minjur',
        district: 'Tiruvallur',
        landmarks: ['Minjur Railway Station'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['121'],
        popularity: 84
      },
      {
        id: 'stop_vinayagapuram',
        name: 'Vinayagapuram Bus Stop',
        nameTamil: 'விநாயகபுரம்',
        lat: 13.135,
        lng: 80.215,
        area: 'Kolathur',
        district: 'Chennai',
        landmarks: ['Retteri Junction'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['142'],
        popularity: 86
      },
      {
        id: 'stop_saligramam',
        name: 'Saligramam Bus Stop',
        nameTamil: 'சாலிகிராமம்',
        lat: 13.055,
        lng: 80.195,
        area: 'Saligramam',
        district: 'Chennai',
        landmarks: ['Prasad Labs'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: [],
        popularity: 87
      },
      {
        id: 'stop_mogalivakkam',
        name: 'Mogalivakkam Bus Stop',
        nameTamil: 'முகலிவாக்கம்',
        lat: 13.025,
        lng: 80.165,
        area: 'Mogalivakkam',
        district: 'Chennai',
        landmarks: ['DLF IT Park'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['26M', '26R'],
        popularity: 89
      },
      {
        id: 'stop_madhavaram',
        name: 'Madhavaram MMBT',
        nameTamil: 'மாதவரம்',
        lat: 13.145,
        lng: 80.235,
        area: 'Madhavaram',
        district: 'Chennai',
        landmarks: ['MMBT Bus Terminus'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['104F', '104M'],
        popularity: 93
      },
      {
        id: 'stop_guduvanchery',
        name: 'Guduvanchery Bus Stand',
        nameTamil: 'கூடுவாஞ்சேரி',
        lat: 12.845,
        lng: 80.065,
        area: 'Guduvanchery',
        district: 'Chengalpattu',
        landmarks: ['Guduvanchery Railway Station'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['104CX'],
        popularity: 92
      },
      {
        id: 'stop_thiruvallur',
        name: 'Thiruvallur Bus Terminus',
        nameTamil: 'திருவள்ளூர்',
        lat: 13.145,
        lng: 79.91,
        area: 'Thiruvallur',
        district: 'Thiruvallur',
        landmarks: ['Veeraraghavaswamy Temple'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['297', '597'],
        popularity: 90
      },
      {
        id: 'stop_chengalpattu',
        name: 'Chengalpattu NT Bus Stand',
        nameTamil: 'செங்கல்பட்டு',
        lat: 12.682,
        lng: 79.982,
        area: 'Chengalpattu',
        district: 'Chengalpattu',
        landmarks: ['Chengalpattu Junction'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['500'],
        popularity: 92
      },
      {
        id: 'stop_sunguvarchathiram',
        name: 'Sunguvarchathiram',
        nameTamil: 'சுங்குவாா்சத்திரம்',
        lat: 12.975,
        lng: 79.88,
        area: 'Sunguvarchathiram',
        district: 'Kanchipuram',
        landmarks: ['SIPCOT Industrial Park'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['578'],
        popularity: 85
      },
      {
        id: 'stop_arani',
        name: 'Arani Bus Stand',
        nameTamil: 'ஆரணி',
        lat: 13.25,
        lng: 80.09,
        area: 'Arani',
        district: 'Tiruvallur',
        landmarks: ['Arani River Bridge'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['580'],
        popularity: 82
      },
      {
        id: 'stop_mamallapuram',
        name: 'Mamallapuram Bus Stand',
        nameTamil: 'மாமல்லபுரம்',
        lat: 12.62,
        lng: 80.19,
        area: 'Mamallapuram',
        district: 'Chengalpattu',
        landmarks: ['Shore Temple'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['588'],
        popularity: 94
      },
      {
        id: 'stop_perambakkam',
        name: 'Perambakkam',
        nameTamil: 'பெரம்பாக்கம்',
        lat: 13.015,
        lng: 79.9,
        area: 'Perambakkam',
        district: 'Tiruvallur',
        landmarks: ['Perambakkam Junction'],
        wheelchairAccessible: true,
        hasShelter: true,
        routes: ['591'],
        popularity: 82
      }
    ];
  }

  private seedRoutes() {
    this.routes = [
      {
        id: 'route_1',
        routeNumber: '1',
        operator: 'MTC',
        origin: 'Broadway',
        originTamil: 'பிராட்வே',
        destination: 'Thiruvanmiyur',
        destinationTamil: 'திருவான்மியூர்',
        stops: ['stop_broadway', 'stop_island_ground', 'stop_marina_beach', 'stop_thiruvanmiyur'],
        polyline: [[13.0878, 80.2835], [13.0722, 80.28], [13.0398, 80.2782], [12.983, 80.2594]],
        avgDurationMins: 45,
        fareRs: 18,
        frequencyMins: 10,
        type: 'ORDINARY'
      },
      {
        id: 'route_2a',
        routeNumber: '2A',
        operator: 'MTC',
        origin: 'Anna Square',
        originTamil: 'அண்ணா சதுக்கம்',
        destination: 'K. Kannadasan Nagar',
        destinationTamil: 'க. கண்ணதாசன் நகர்',
        stops: ['stop_island_ground', 'stop_broadway', 'stop_kannadasan_nagar'],
        polyline: [[13.0722, 80.28], [13.0878, 80.2835], [13.1345, 80.2465]],
        avgDurationMins: 40,
        fareRs: 16,
        frequencyMins: 12,
        type: 'ORDINARY'
      },
      {
        id: 'route_2b',
        routeNumber: '2B',
        operator: 'MTC',
        origin: 'K. Kannadasan Nagar',
        originTamil: 'க. கண்ணதாசன் நகர்',
        destination: 'K. Kannadasan Nagar',
        destinationTamil: 'க. கண்ணதாசன் நகர்',
        stops: ['stop_kannadasan_nagar', 'stop_broadway', 'stop_kannadasan_nagar'],
        polyline: [[13.1345, 80.2465], [13.0878, 80.2835], [13.1345, 80.2465]],
        avgDurationMins: 50,
        fareRs: 18,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_3',
        routeNumber: '3',
        operator: 'MTC',
        origin: 'T. Nagar',
        originTamil: 'தி. நகர்',
        destination: 'Thiruvanmiyur',
        destinationTamil: 'திருவான்மியூர்',
        stops: ['stop_t_nagar_terminus', 'stop_velachery', 'stop_thiruvanmiyur'],
        polyline: [[13.0418, 80.2341], [12.978, 80.222], [12.983, 80.2594]],
        avgDurationMins: 35,
        fareRs: 16,
        frequencyMins: 8,
        type: 'ORDINARY'
      },
      {
        id: 'route_4',
        routeNumber: '4',
        operator: 'MTC',
        origin: 'Island Ground',
        originTamil: 'தீவு திடல்',
        destination: 'Ennore',
        destinationTamil: 'எண்ணூர்',
        stops: ['stop_island_ground', 'stop_broadway', 'stop_ennore'],
        polyline: [[13.0722, 80.28], [13.0878, 80.2835], [13.2145, 80.321]],
        avgDurationMins: 55,
        fareRs: 22,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_8b',
        routeNumber: '8B',
        operator: 'MTC',
        origin: 'Island Ground',
        originTamil: 'தீவு திடல்',
        destination: 'Thiru.Vi.Ka. Nagar',
        destinationTamil: 'திரு.வி.க. நகர்',
        stops: ['stop_island_ground', 'stop_broadway', 'stop_thiruvika_nagar'],
        polyline: [[13.0722, 80.28], [13.0878, 80.2835], [13.1154, 80.2356]],
        avgDurationMins: 38,
        fareRs: 16,
        frequencyMins: 10,
        type: 'ORDINARY'
      },
      {
        id: 'route_13',
        routeNumber: '13',
        operator: 'MTC',
        origin: 'T. Nagar',
        originTamil: 'தி. நகர்',
        destination: 'Island Ground',
        destinationTamil: 'தீவு திடல்',
        stops: ['stop_t_nagar_terminus', 'stop_island_ground'],
        polyline: [[13.0418, 80.2341], [13.0722, 80.28]],
        avgDurationMins: 30,
        fareRs: 14,
        frequencyMins: 10,
        type: 'ORDINARY'
      },
      {
        id: 'route_15',
        routeNumber: '15',
        operator: 'MTC',
        origin: 'Island Ground',
        originTamil: 'தீவு திடல்',
        destination: 'CMBT Koyambedu',
        destinationTamil: 'கோயம்பேடு',
        stops: ['stop_island_ground', 'stop_cmbt'],
        polyline: [[13.0722, 80.28], [13.0694, 80.1948]],
        avgDurationMins: 35,
        fareRs: 16,
        frequencyMins: 10,
        type: 'ORDINARY'
      },
      {
        id: 'route_18a',
        routeNumber: '18A',
        operator: 'MTC',
        origin: 'Royapuram',
        originTamil: 'ராயபுரம்',
        destination: 'Kilambakkam KCBT',
        destinationTamil: 'கிளம்பாக்கம்',
        stops: ['stop_royapuram', 'stop_broadway', 'stop_guindy', 'stop_tambaram_west', 'stop_kilambakkam'],
        polyline: [[13.1112, 80.2925], [13.0878, 80.2835], [13.0067, 80.202], [12.925, 80.1171], [12.8342, 80.0768]],
        avgDurationMins: 80,
        fareRs: 35,
        frequencyMins: 10,
        type: 'EXPRESS'
      },
      {
        id: 'route_19',
        routeNumber: '19',
        operator: 'MTC',
        origin: 'T. Nagar',
        originTamil: 'தி. நகர்',
        destination: 'Thiruporur',
        destinationTamil: 'திருப்போரூர்',
        stops: ['stop_t_nagar_terminus', 'stop_siruseri', 'stop_thiruporur'],
        polyline: [[13.0418, 80.2341], [12.8285, 80.2185], [12.7245, 80.1912]],
        avgDurationMins: 75,
        fareRs: 32,
        frequencyMins: 12,
        type: 'EXPRESS'
      },
      {
        id: 'route_19a',
        routeNumber: '19A',
        operator: 'MTC',
        origin: 'T. Nagar',
        originTamil: 'தி. நகர்',
        destination: 'Siruseri IT Corridor',
        destinationTamil: 'சிறுசேரி',
        stops: ['stop_t_nagar_terminus', 'stop_siruseri'],
        polyline: [[13.0418, 80.2341], [12.8285, 80.2185]],
        avgDurationMins: 55,
        fareRs: 26,
        frequencyMins: 8,
        type: 'DELUXE'
      },
      {
        id: 'route_19b',
        routeNumber: '19B',
        operator: 'MTC',
        origin: 'T. Nagar',
        originTamil: 'தி. நகர்',
        destination: 'Thiruporur Area',
        destinationTamil: 'திருப்போரூர்',
        stops: ['stop_t_nagar_terminus', 'stop_siruseri', 'stop_thiruporur'],
        polyline: [[13.0418, 80.2341], [12.8285, 80.2185], [12.7245, 80.1912]],
        avgDurationMins: 75,
        fareRs: 32,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_19c',
        routeNumber: '19C',
        operator: 'MTC',
        origin: 'T. Nagar',
        originTamil: 'தி. நகர்',
        destination: 'Siruseri OMR',
        destinationTamil: 'சிறுசேரி OMR',
        stops: ['stop_t_nagar_terminus', 'stop_siruseri'],
        polyline: [[13.0418, 80.2341], [12.8285, 80.2185]],
        avgDurationMins: 55,
        fareRs: 26,
        frequencyMins: 10,
        type: 'DELUXE'
      },
      {
        id: 'route_19d',
        routeNumber: '19D',
        operator: 'MTC',
        origin: 'T. Nagar',
        originTamil: 'தி. நகர்',
        destination: 'Kovalam OMR',
        destinationTamil: 'கோவளம் OMR',
        stops: ['stop_t_nagar_terminus', 'stop_siruseri', 'stop_kovalam'],
        polyline: [[13.0418, 80.2341], [12.8285, 80.2185], [12.79, 80.25]],
        avgDurationMins: 65,
        fareRs: 28,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_19t',
        routeNumber: '19T',
        operator: 'MTC',
        origin: 'T. Nagar',
        originTamil: 'தி. நகர்',
        destination: 'Kelambakkam OMR',
        destinationTamil: 'கேளம்பாக்கம் OMR',
        stops: ['stop_t_nagar_terminus', 'stop_siruseri', 'stop_kelambakkam'],
        polyline: [[13.0418, 80.2341], [12.8285, 80.2185], [12.785, 80.222]],
        avgDurationMins: 65,
        fareRs: 28,
        frequencyMins: 12,
        type: 'ORDINARY'
      },
      {
        id: 'route_21',
        routeNumber: '21',
        operator: 'MTC',
        origin: 'Broadway',
        originTamil: 'பிராட்வே',
        destination: 'Mandaveli',
        destinationTamil: 'மந்தவெளி',
        stops: ['stop_broadway', 'stop_island_ground', 'stop_mandaveli'],
        polyline: [[13.0878, 80.2835], [13.0722, 80.28], [13.028, 80.26]],
        avgDurationMins: 35,
        fareRs: 15,
        frequencyMins: 10,
        type: 'ORDINARY'
      },
      {
        id: 'route_21c',
        routeNumber: '21C',
        operator: 'MTC',
        origin: 'Broadway',
        originTamil: 'பிராட்வே',
        destination: 'Kannagi Nagar',
        destinationTamil: 'கண்ணகி நகர்',
        stops: ['stop_broadway', 'stop_island_ground', 'stop_kannagi_nagar'],
        polyline: [[13.0878, 80.2835], [13.0722, 80.28], [12.935, 80.23]],
        avgDurationMins: 45,
        fareRs: 18,
        frequencyMins: 12,
        type: 'ORDINARY'
      },
      {
        id: 'route_21e',
        routeNumber: '21E',
        operator: 'MTC',
        origin: 'Island Ground',
        originTamil: 'தீவு திடல்',
        destination: 'Ramapuram',
        destinationTamil: 'ராமாபுரம்',
        stops: ['stop_island_ground', 'stop_guindy', 'stop_ramapuram'],
        polyline: [[13.0722, 80.28], [13.0067, 80.202], [13.0385, 80.1785]],
        avgDurationMins: 40,
        fareRs: 16,
        frequencyMins: 12,
        type: 'ORDINARY'
      },
      {
        id: 'route_21g',
        routeNumber: '21G',
        operator: 'MTC',
        origin: 'Island Ground',
        originTamil: 'தீவு திடல்',
        destination: 'Kilambakkam KCBT',
        destinationTamil: 'கிளம்பாக்கம்',
        stops: ['stop_island_ground', 'stop_guindy', 'stop_tambaram_west', 'stop_kilambakkam'],
        polyline: [[13.0722, 80.28], [13.0067, 80.202], [12.925, 80.1171], [12.8342, 80.0768]],
        avgDurationMins: 70,
        fareRs: 30,
        frequencyMins: 8,
        type: 'EXPRESS'
      },
      {
        id: 'route_21l',
        routeNumber: '21L',
        operator: 'MTC',
        origin: 'Broadway',
        originTamil: 'பிராட்வே',
        destination: 'Velachery',
        destinationTamil: 'வேளச்சேரி',
        stops: ['stop_broadway', 'stop_island_ground', 'stop_velachery'],
        polyline: [[13.0878, 80.2835], [13.0722, 80.28], [12.978, 80.222]],
        avgDurationMins: 45,
        fareRs: 18,
        frequencyMins: 10,
        type: 'ORDINARY'
      },
      {
        id: 'route_21x',
        routeNumber: '21X',
        operator: 'MTC',
        origin: 'Broadway',
        originTamil: 'பிராட்வே',
        destination: 'Guindy',
        destinationTamil: 'கிண்டி',
        stops: ['stop_broadway', 'stop_island_ground', 'stop_guindy'],
        polyline: [[13.0878, 80.2835], [13.0722, 80.28], [13.0067, 80.202]],
        avgDurationMins: 35,
        fareRs: 15,
        frequencyMins: 8,
        type: 'ORDINARY'
      },
      {
        id: 'route_22',
        routeNumber: '22',
        operator: 'MTC',
        origin: 'Anna Square',
        originTamil: 'அண்ணா சதுக்கம்',
        destination: 'Korattur / Villivakkam',
        destinationTamil: 'கொரட்டூர்',
        stops: ['stop_island_ground', 'stop_korattur'],
        polyline: [[13.0722, 80.28], [13.11, 80.19]],
        avgDurationMins: 45,
        fareRs: 18,
        frequencyMins: 12,
        type: 'ORDINARY'
      },
      {
        id: 'route_23c',
        routeNumber: '23C',
        operator: 'MTC',
        origin: 'Besant Nagar',
        originTamil: 'பெசன்ட் நகர்',
        destination: 'Ayanavaram',
        destinationTamil: 'அயனாவரம்',
        stops: ['stop_besant_nagar', 'stop_t_nagar_terminus', 'stop_kodambakkam', 'stop_valluvar_kottam', 'stop_ayanavaram'],
        polyline: [[13.0003, 80.2667], [13.0418, 80.2341], [13.0514, 80.2245], [13.0583, 80.2415], [13.0985, 80.2385]],
        avgDurationMins: 45,
        fareRs: 18,
        frequencyMins: 10,
        type: 'ORDINARY'
      },
      {
        id: 'route_23v',
        routeNumber: '23V',
        operator: 'MTC',
        origin: 'Velachery',
        originTamil: 'வேளச்சேரி',
        destination: 'Villivakkam',
        destinationTamil: 'வில்லிவாக்கம்',
        stops: ['stop_velachery', 'stop_guindy', 'stop_icf', 'stop_korattur'],
        polyline: [[12.978, 80.222], [13.0067, 80.202], [13.098, 80.218], [13.11, 80.19]],
        avgDurationMins: 50,
        fareRs: 20,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_24a',
        routeNumber: '24A',
        operator: 'MTC',
        origin: 'Vivekananda House',
        originTamil: 'விவேகானந்தர் இல்லம்',
        destination: 'Anna Nagar West',
        destinationTamil: 'அண்ணா நகர் மேற்கு',
        stops: ['stop_vivekananda_house', 'stop_island_ground', 'stop_anna_nagar_west'],
        polyline: [[13.053, 80.28], [13.0722, 80.28], [13.088, 80.208]],
        avgDurationMins: 45,
        fareRs: 18,
        frequencyMins: 12,
        type: 'ORDINARY'
      },
      {
        id: 'route_25',
        routeNumber: '25',
        operator: 'MTC',
        origin: 'Anna Square',
        originTamil: 'அண்ணா சதுக்கம்',
        destination: 'Poonamallee',
        destinationTamil: 'பூவிருந்தவல்லி',
        stops: ['stop_island_ground', 'stop_kodambakkam', 'stop_valasaravakkam', 'stop_porur', 'stop_poonamallee'],
        polyline: [[13.0722, 80.28], [13.0514, 80.2245], [13.0425, 80.1885], [13.0335, 80.1582], [13.0485, 80.0912]],
        avgDurationMins: 60,
        fareRs: 24,
        frequencyMins: 10,
        type: 'ORDINARY'
      },
      {
        id: 'route_26',
        routeNumber: '26',
        operator: 'MTC',
        origin: 'Royapuram',
        originTamil: 'ராயபுரம்',
        destination: 'Iyyappanthangal',
        destinationTamil: 'அய்யப்பன்தாங்கல்',
        stops: ['stop_royapuram', 'stop_broadway', 'stop_kodambakkam', 'stop_iyyappanthangal'],
        polyline: [[13.1112, 80.2925], [13.0878, 80.2835], [13.0514, 80.2245], [13.0385, 80.1385]],
        avgDurationMins: 55,
        fareRs: 22,
        frequencyMins: 10,
        type: 'ORDINARY'
      },
      {
        id: 'route_26b',
        routeNumber: '26B',
        operator: 'MTC',
        origin: 'Royapuram',
        originTamil: 'ராயபுரம்',
        destination: 'Mangadu',
        destinationTamil: 'மாங்காடு',
        stops: ['stop_royapuram', 'stop_broadway', 'stop_porur', 'stop_mangadu'],
        polyline: [[13.1112, 80.2925], [13.0878, 80.2835], [13.0335, 80.1582], [13.0112, 80.1154]],
        avgDurationMins: 55,
        fareRs: 22,
        frequencyMins: 12,
        type: 'ORDINARY'
      },
      {
        id: 'route_26g',
        routeNumber: '26G',
        operator: 'MTC',
        origin: 'Royapuram',
        originTamil: 'ராயபுரம்',
        destination: 'Iyyappanthangal',
        destinationTamil: 'அய்யப்பன்தாங்கல்',
        stops: ['stop_royapuram', 'stop_broadway', 'stop_iyyappanthangal'],
        polyline: [[13.1112, 80.2925], [13.0878, 80.2835], [13.0385, 80.1385]],
        avgDurationMins: 55,
        fareRs: 22,
        frequencyMins: 12,
        type: 'ORDINARY'
      },
      {
        id: 'route_26k',
        routeNumber: '26K',
        operator: 'MTC',
        origin: 'Royapuram',
        originTamil: 'ராயபுரம்',
        destination: 'Iyyappanthangal',
        destinationTamil: 'அய்யப்பன்தாங்கல்',
        stops: ['stop_royapuram', 'stop_broadway', 'stop_iyyappanthangal'],
        polyline: [[13.1112, 80.2925], [13.0878, 80.2835], [13.0385, 80.1385]],
        avgDurationMins: 55,
        fareRs: 22,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_26m',
        routeNumber: '26M',
        operator: 'MTC',
        origin: 'Royapuram',
        originTamil: 'ராயபுரம்',
        destination: 'Mogalivakkam',
        destinationTamil: 'முகலிவாக்கம்',
        stops: ['stop_royapuram', 'stop_broadway', 'stop_porur', 'stop_mogalivakkam'],
        polyline: [[13.1112, 80.2925], [13.0878, 80.2835], [13.0335, 80.1582], [13.025, 80.165]],
        avgDurationMins: 50,
        fareRs: 20,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_26r',
        routeNumber: '26R',
        operator: 'MTC',
        origin: 'Royapuram',
        originTamil: 'ராயபுரம்',
        destination: 'Mogalivakkam',
        destinationTamil: 'முகலிவாக்கம்',
        stops: ['stop_royapuram', 'stop_broadway', 'stop_porur', 'stop_mogalivakkam'],
        polyline: [[13.1112, 80.2925], [13.0878, 80.2835], [13.0335, 80.1582], [13.025, 80.165]],
        avgDurationMins: 50,
        fareRs: 20,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_27b',
        routeNumber: '27B',
        operator: 'MTC',
        origin: 'CMBT Koyambedu',
        originTamil: 'கோயம்பேடு',
        destination: 'Anna Square',
        destinationTamil: 'அண்ணா சதுக்கம்',
        stops: ['stop_cmbt', 'stop_vadapalani', 'stop_power_house', 'stop_kodambakkam', 'stop_valluvar_kottam', 'stop_island_ground'],
        polyline: [[13.0694, 80.1948], [13.05, 80.2121], [13.0482, 80.2175], [13.0514, 80.2245], [13.0583, 80.2415], [13.0722, 80.28]],
        avgDurationMins: 35,
        fareRs: 16,
        frequencyMins: 8,
        type: 'ORDINARY'
      },
      {
        id: 'route_29a',
        routeNumber: '29A',
        operator: 'MTC',
        origin: 'Perambur',
        originTamil: 'பெரம்பூர்',
        destination: 'Anna Square',
        destinationTamil: 'அண்ணா சதுக்கம்',
        stops: ['stop_perambur', 'stop_broadway', 'stop_island_ground'],
        polyline: [[13.1095, 80.2485], [13.0878, 80.2835], [13.0722, 80.28]],
        avgDurationMins: 40,
        fareRs: 16,
        frequencyMins: 12,
        type: 'ORDINARY'
      },
      {
        id: 'route_29c',
        routeNumber: '29C',
        operator: 'MTC',
        origin: 'Perambur',
        originTamil: 'பெரம்பூர்',
        destination: 'Besant Nagar',
        destinationTamil: 'பெசன்ட் நகர்',
        stops: ['stop_perambur', 'stop_besant_nagar'],
        polyline: [[13.1095, 80.2485], [13.0003, 80.2667]],
        avgDurationMins: 45,
        fareRs: 18,
        frequencyMins: 10,
        type: 'ORDINARY'
      },
      {
        id: 'route_31g',
        routeNumber: '31G',
        operator: 'MTC',
        origin: 'Tambaram West',
        originTamil: 'தாம்பரம் மேற்கு',
        destination: 'Medavakkam Road',
        destinationTamil: 'மேடவாக்கம்',
        stops: ['stop_tambaram_west', 'stop_medavakkam_rd'],
        polyline: [[12.925, 80.1171], [12.918, 80.192]],
        avgDurationMins: 30,
        fareRs: 14,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_32a',
        routeNumber: '32A',
        operator: 'MTC',
        origin: 'Tondiarpet',
        originTamil: 'தண்டையார்பேட்டை',
        destination: 'Vivekananda House',
        destinationTamil: 'விவேகானந்தர் இல்லம்',
        stops: ['stop_tondiarpet', 'stop_vallalar_nagar', 'stop_vivekananda_house'],
        polyline: [[13.128, 80.288], [13.105, 80.282], [13.053, 80.28]],
        avgDurationMins: 35,
        fareRs: 15,
        frequencyMins: 12,
        type: 'ORDINARY'
      },
      {
        id: 'route_32b',
        routeNumber: '32B',
        operator: 'MTC',
        origin: 'Korukkupet',
        originTamil: 'கொருக்குப்பேட்டை',
        destination: 'Vivekananda House',
        destinationTamil: 'விவேகானந்தர் இல்லம்',
        stops: ['stop_korukkupet', 'stop_vallalar_nagar', 'stop_vivekananda_house'],
        polyline: [[13.118, 80.278], [13.105, 80.282], [13.053, 80.28]],
        avgDurationMins: 35,
        fareRs: 15,
        frequencyMins: 12,
        type: 'ORDINARY'
      },
      {
        id: 'route_34',
        routeNumber: '34',
        operator: 'MTC',
        origin: 'Ambattur Industrial Estate',
        originTamil: 'அம்பத்தூர் தொழிற்பேட்டை',
        destination: 'Thiruvotriyur',
        destinationTamil: 'திருவொற்றியூர்',
        stops: ['stop_ambattur_ie', 'stop_thiruvotriyur'],
        polyline: [[13.1012, 80.1612], [13.1612, 80.3012]],
        avgDurationMins: 50,
        fareRs: 20,
        frequencyMins: 12,
        type: 'ORDINARY'
      },
      {
        id: 'route_37',
        routeNumber: '37',
        operator: 'MTC',
        origin: 'Vallalar Nagar',
        originTamil: 'வள்ளலார் நகர்',
        destination: 'Poonamallee',
        destinationTamil: 'பூவிருந்தவல்லி',
        stops: ['stop_vallalar_nagar', 'stop_vadapalani', 'stop_porur', 'stop_poonamallee'],
        polyline: [[13.105, 80.282], [13.05, 80.2121], [13.0335, 80.1582], [13.0485, 80.0912]],
        avgDurationMins: 55,
        fareRs: 22,
        frequencyMins: 10,
        type: 'ORDINARY'
      },
      {
        id: 'route_40a',
        routeNumber: '40A',
        operator: 'MTC',
        origin: 'Anna Square',
        originTamil: 'அண்ணா சதுக்கம்',
        destination: 'Pattabiram',
        destinationTamil: 'பட்டாபிராம்',
        stops: ['stop_island_ground', 'stop_pattabiram'],
        polyline: [[13.0722, 80.28], [13.1245, 80.0612]],
        avgDurationMins: 65,
        fareRs: 26,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_40h',
        routeNumber: '40H',
        operator: 'MTC',
        origin: 'Anna Square',
        originTamil: 'அண்ணா சதுக்கம்',
        destination: 'Pattabiram',
        destinationTamil: 'பட்டாபிராம்',
        stops: ['stop_island_ground', 'stop_pattabiram'],
        polyline: [[13.0722, 80.28], [13.1245, 80.0612]],
        avgDurationMins: 60,
        fareRs: 24,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_44',
        routeNumber: '44',
        operator: 'MTC',
        origin: 'Island Ground',
        originTamil: 'தீவு திடல்',
        destination: 'Manali',
        destinationTamil: 'மணலி',
        stops: ['stop_island_ground', 'stop_vallalar_nagar', 'stop_manali'],
        polyline: [[13.0722, 80.28], [13.105, 80.282], [13.168, 80.262]],
        avgDurationMins: 45,
        fareRs: 18,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_45a',
        routeNumber: '45A',
        operator: 'MTC',
        origin: 'Vivekananda House',
        originTamil: 'விவேகானந்தர் இல்லம்',
        destination: 'Madipakkam',
        destinationTamil: 'மடிப்பாக்கம்',
        stops: ['stop_vivekananda_house', 'stop_guindy', 'stop_madipakkam'],
        polyline: [[13.053, 80.28], [13.0067, 80.202], [12.965, 80.198]],
        avgDurationMins: 45,
        fareRs: 18,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_45b',
        routeNumber: '45B',
        operator: 'MTC',
        origin: 'Anna Square',
        originTamil: 'அண்ணா சதுக்கம்',
        destination: 'Guindy TVK Estate',
        destinationTamil: 'கிண்டி',
        stops: ['stop_island_ground', 'stop_marina_beach', 'stop_guindy'],
        polyline: [[13.0722, 80.28], [13.0398, 80.2782], [13.0067, 80.202]],
        avgDurationMins: 35,
        fareRs: 15,
        frequencyMins: 10,
        type: 'ORDINARY'
      },
      {
        id: 'route_45e',
        routeNumber: '45E',
        operator: 'MTC',
        origin: 'Anna Square',
        originTamil: 'அண்ணா சதுக்கம்',
        destination: 'Kilkattalai',
        destinationTamil: 'கீழ்க்கட்டளை',
        stops: ['stop_island_ground', 'stop_guindy', 'stop_kilkattalai'],
        polyline: [[13.0722, 80.28], [13.0067, 80.202], [12.955, 80.188]],
        avgDurationMins: 50,
        fareRs: 20,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_47t',
        routeNumber: '47T',
        operator: 'MTC',
        origin: 'T. Nagar',
        originTamil: 'தி. நகர்',
        destination: 'ICF Villivakkam',
        destinationTamil: 'ஐ.சி.எஃப்',
        stops: ['stop_t_nagar_terminus', 'stop_icf'],
        polyline: [[13.0418, 80.2341], [13.098, 80.218]],
        avgDurationMins: 35,
        fareRs: 15,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_49a',
        routeNumber: '49A',
        operator: 'MTC',
        origin: 'T. Nagar',
        originTamil: 'தி. நகர்',
        destination: 'Poonamallee',
        destinationTamil: 'பூவிருந்தவல்லி',
        stops: ['stop_t_nagar_terminus', 'stop_iyyappanthangal', 'stop_poonamallee'],
        polyline: [[13.0418, 80.2341], [13.0385, 80.1385], [13.0485, 80.0912]],
        avgDurationMins: 45,
        fareRs: 18,
        frequencyMins: 12,
        type: 'ORDINARY'
      },
      {
        id: 'route_50',
        routeNumber: '50',
        operator: 'MTC',
        origin: 'Royapuram',
        originTamil: 'ராயபுரம்',
        destination: 'Thiruverkadu',
        destinationTamil: 'திருவேற்காடு',
        stops: ['stop_royapuram', 'stop_broadway', 'stop_thiruverkadu'],
        polyline: [[13.1112, 80.2925], [13.0878, 80.2835], [13.072, 80.122]],
        avgDurationMins: 50,
        fareRs: 20,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_54',
        routeNumber: '54',
        operator: 'MTC',
        origin: 'Royapuram',
        originTamil: 'ராயபுரம்',
        destination: 'Poonamallee',
        destinationTamil: 'பூவிருந்தவல்லி',
        stops: ['stop_royapuram', 'stop_porur', 'stop_poonamallee'],
        polyline: [[13.1112, 80.2925], [13.0335, 80.1582], [13.0485, 80.0912]],
        avgDurationMins: 60,
        fareRs: 24,
        frequencyMins: 10,
        type: 'ORDINARY'
      },
      {
        id: 'route_57',
        routeNumber: '57',
        operator: 'MTC',
        origin: 'Vallalar Nagar',
        originTamil: 'வள்ளலார் நகர்',
        destination: 'Redhills',
        destinationTamil: 'ரெட்ஹில்ஸ்',
        stops: ['stop_vallalar_nagar', 'stop_redhills'],
        polyline: [[13.105, 80.282], [13.198, 80.198]],
        avgDurationMins: 45,
        fareRs: 18,
        frequencyMins: 12,
        type: 'ORDINARY'
      },
      {
        id: 'route_60a',
        routeNumber: '60A',
        operator: 'MTC',
        origin: 'Royapuram',
        originTamil: 'ராயபுரம்',
        destination: 'Kundrathur',
        destinationTamil: 'குன்றத்தூர்',
        stops: ['stop_royapuram', 'stop_broadway', 'stop_guindy', 'stop_kundrathur'],
        polyline: [[13.1112, 80.2925], [13.0878, 80.2835], [13.0067, 80.202], [12.9978, 80.0972]],
        avgDurationMins: 60,
        fareRs: 24,
        frequencyMins: 12,
        type: 'ORDINARY'
      },
      {
        id: 'route_66',
        routeNumber: '66',
        operator: 'MTC',
        origin: 'Tambaram West',
        originTamil: 'தாம்பரம் மேற்கு',
        destination: 'Poonamallee',
        destinationTamil: 'பூவிருந்தவல்லி',
        stops: ['stop_tambaram_west', 'stop_kundrathur', 'stop_poonamallee'],
        polyline: [[12.925, 80.1171], [12.9978, 80.0972], [13.0485, 80.0912]],
        avgDurationMins: 45,
        fareRs: 18,
        frequencyMins: 12,
        type: 'ORDINARY'
      },
      {
        id: 'route_66a',
        routeNumber: '66A',
        operator: 'MTC',
        origin: 'Hasthinapuram',
        originTamil: 'ஹஸ்தினாபுரம்',
        destination: 'Kundrathur',
        destinationTamil: 'குன்றத்தூர்',
        stops: ['stop_hasthinapuram', 'stop_kundrathur'],
        polyline: [[12.945, 80.145], [12.9978, 80.0972]],
        avgDurationMins: 35,
        fareRs: 15,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_66j',
        routeNumber: '66J',
        operator: 'MTC',
        origin: 'Tambaram West',
        originTamil: 'தாம்பரம் மேற்கு',
        destination: 'Poonamallee',
        destinationTamil: 'பூவிருந்தவல்லி',
        stops: ['stop_tambaram_west', 'stop_poonamallee'],
        polyline: [[12.925, 80.1171], [13.0485, 80.0912]],
        avgDurationMins: 45,
        fareRs: 18,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_72',
        routeNumber: '72',
        operator: 'MTC',
        origin: 'T. Nagar',
        originTamil: 'தி. நகர்',
        destination: 'Thiruverkadu',
        destinationTamil: 'திருவேற்காடு',
        stops: ['stop_t_nagar_terminus', 'stop_thiruverkadu'],
        polyline: [[13.0418, 80.2341], [13.072, 80.122]],
        avgDurationMins: 40,
        fareRs: 16,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_77',
        routeNumber: '77',
        operator: 'MTC',
        origin: 'Avadi',
        originTamil: 'ஆவடி',
        destination: 'CMBT Koyambedu',
        destinationTamil: 'கோயம்பேடு',
        stops: ['stop_avadi', 'stop_cmbt'],
        polyline: [[13.115, 80.1], [13.0694, 80.1948]],
        avgDurationMins: 40,
        fareRs: 16,
        frequencyMins: 12,
        type: 'ORDINARY'
      },
      {
        id: 'route_78',
        routeNumber: '78',
        operator: 'MTC',
        origin: 'CMBT Koyambedu',
        originTamil: 'கோயம்பேடு',
        destination: 'Thiruvanmiyur',
        destinationTamil: 'திருவான்மியூர்',
        stops: ['stop_cmbt', 'stop_guindy', 'stop_thiruvanmiyur'],
        polyline: [[13.0694, 80.1948], [13.0067, 80.202], [12.983, 80.2594]],
        avgDurationMins: 45,
        fareRs: 18,
        frequencyMins: 12,
        type: 'ORDINARY'
      },
      {
        id: 'route_85',
        routeNumber: '85',
        operator: 'MTC',
        origin: 'CMBT Koyambedu',
        originTamil: 'கோயம்பேடு',
        destination: 'Kundrathur',
        destinationTamil: 'குன்றத்தூர்',
        stops: ['stop_cmbt', 'stop_porur', 'stop_kundrathur'],
        polyline: [[13.0694, 80.1948], [13.0335, 80.1582], [12.9978, 80.0972]],
        avgDurationMins: 45,
        fareRs: 18,
        frequencyMins: 12,
        type: 'ORDINARY'
      },
      {
        id: 'route_88k',
        routeNumber: '88K',
        operator: 'MTC',
        origin: 'Kundrathur',
        originTamil: 'குன்றத்தூர்',
        destination: 'Broadway',
        destinationTamil: 'பிராட்வே',
        stops: ['stop_kundrathur', 'stop_mangadu', 'stop_porur', 'stop_ramapuram', 'stop_valasaravakkam', 'stop_vadapalani', 'stop_ashok_pillar', 'stop_power_house', 'stop_kodambakkam_rs', 'stop_kodambakkam'],
        polyline: [[12.9978, 80.0972], [13.0112, 80.1154], [13.0335, 80.1582], [13.0385, 80.1785], [13.0425, 80.1885], [13.05, 80.2121], [13.0352, 80.2123], [13.0482, 80.2175], [13.0518, 80.2268], [13.0514, 80.2245]],
        avgDurationMins: 45,
        fareRs: 22,
        frequencyMins: 10,
        type: 'ORDINARY'
      },
      {
        id: 'route_88ket',
        routeNumber: '88KET',
        operator: 'MTC',
        origin: 'Broadway',
        originTamil: 'பிராட்வே',
        destination: 'Nallur',
        destinationTamil: 'நல்லூர்',
        stops: ['stop_broadway', 'stop_kundrathur', 'stop_nallur'],
        polyline: [[13.0878, 80.2835], [12.9978, 80.0972], [12.98, 80.06]],
        avgDurationMins: 55,
        fareRs: 25,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_88m',
        routeNumber: '88M',
        operator: 'MTC',
        origin: 'Vadapalani',
        originTamil: 'வடபழனி',
        destination: 'Somangalam',
        destinationTamil: 'சோமங்கலம்',
        stops: ['stop_vadapalani', 'stop_kundrathur', 'stop_somangalam'],
        polyline: [[13.05, 80.2121], [12.9978, 80.0972], [12.96, 80.04]],
        avgDurationMins: 50,
        fareRs: 22,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_88r',
        routeNumber: '88R',
        operator: 'MTC',
        origin: 'Broadway',
        originTamil: 'பிராட்வே',
        destination: 'Amarambedu',
        destinationTamil: 'அமரம்பேடு',
        stops: ['stop_broadway', 'stop_kundrathur', 'stop_amarambedu'],
        polyline: [[13.0878, 80.2835], [12.9978, 80.0972], [12.95, 80.03]],
        avgDurationMins: 55,
        fareRs: 25,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_89t',
        routeNumber: '89T',
        operator: 'MTC',
        origin: 'Tambaram West',
        originTamil: 'தாம்பரம் மேற்கு',
        destination: 'Kundrathur',
        destinationTamil: 'குன்றத்தூர்',
        stops: ['stop_tambaram_west', 'stop_kundrathur'],
        polyline: [[12.925, 80.1171], [12.9978, 80.0972]],
        avgDurationMins: 35,
        fareRs: 15,
        frequencyMins: 12,
        type: 'ORDINARY'
      },
      {
        id: 'route_91',
        routeNumber: '91',
        operator: 'MTC',
        origin: 'Kilambakkam KCBT',
        originTamil: 'கிளம்பாக்கம்',
        destination: 'Thiruvanmiyur',
        destinationTamil: 'திருவான்மியூர்',
        stops: ['stop_kilambakkam', 'stop_thiruvanmiyur'],
        polyline: [[12.8342, 80.0768], [12.983, 80.2594]],
        avgDurationMins: 60,
        fareRs: 25,
        frequencyMins: 12,
        type: 'EXPRESS'
      },
      {
        id: 'route_96',
        routeNumber: '96',
        operator: 'MTC',
        origin: 'Adyar',
        originTamil: 'அடையாறு',
        destination: 'Tambaram West',
        destinationTamil: 'தாம்பரம் மேற்கு',
        stops: ['stop_adyar', 'stop_tambaram_west'],
        polyline: [[13.006, 80.257], [12.925, 80.1171]],
        avgDurationMins: 45,
        fareRs: 18,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_99',
        routeNumber: '99',
        operator: 'MTC',
        origin: 'Tambaram West',
        originTamil: 'தாம்பரம் மேற்கு',
        destination: 'Adyar',
        destinationTamil: 'அடையாறு',
        stops: ['stop_tambaram_west', 'stop_adyar'],
        polyline: [[12.925, 80.1171], [13.006, 80.257]],
        avgDurationMins: 45,
        fareRs: 18,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_101',
        routeNumber: '101',
        operator: 'MTC',
        origin: 'Thiruvotriyur',
        originTamil: 'திருவொற்றியூர்',
        destination: 'Poonamallee',
        destinationTamil: 'பூவிருந்தவல்லி',
        stops: ['stop_thiruvotriyur', 'stop_broadway', 'stop_poonamallee'],
        polyline: [[13.1612, 80.3012], [13.0878, 80.2835], [13.0485, 80.0912]],
        avgDurationMins: 65,
        fareRs: 26,
        frequencyMins: 12,
        type: 'ORDINARY'
      },
      {
        id: 'route_102',
        routeNumber: '102',
        operator: 'MTC',
        origin: 'Island Ground',
        originTamil: 'தீவு திடல்',
        destination: 'Kelambakkam',
        destinationTamil: 'கேளம்பாக்கம்',
        stops: ['stop_island_ground', 'stop_siruseri', 'stop_thiruporur'],
        polyline: [[13.0722, 80.28], [12.8285, 80.2185], [12.7245, 80.1912]],
        avgDurationMins: 70,
        fareRs: 30,
        frequencyMins: 8,
        type: 'EXPRESS'
      },
      {
        id: 'route_102a',
        routeNumber: '102A',
        operator: 'MTC',
        origin: 'Thiruvanmiyur',
        originTamil: 'திருவான்மியூர்',
        destination: 'Pudupakkam',
        destinationTamil: 'புதுப்பாக்கம்',
        stops: ['stop_thiruvanmiyur', 'stop_pudupakkam'],
        polyline: [[12.983, 80.2594], [12.805, 80.208]],
        avgDurationMins: 50,
        fareRs: 20,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_102c',
        routeNumber: '102C',
        operator: 'MTC',
        origin: 'Island Ground',
        originTamil: 'தீவு திடல்',
        destination: 'Semmancheri',
        destinationTamil: 'செம்மஞ்சேரி',
        stops: ['stop_island_ground', 'stop_semmancheri'],
        polyline: [[13.0722, 80.28], [12.868, 80.225]],
        avgDurationMins: 50,
        fareRs: 20,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_102ct',
        routeNumber: '102CT',
        operator: 'MTC',
        origin: 'Thiruvanmiyur',
        originTamil: 'திருவான்மியூர்',
        destination: 'Siruseri IT Park',
        destinationTamil: 'சிறுசேரி',
        stops: ['stop_thiruvanmiyur', 'stop_siruseri'],
        polyline: [[12.983, 80.2594], [12.8285, 80.2185]],
        avgDurationMins: 45,
        fareRs: 18,
        frequencyMins: 10,
        type: 'DELUXE'
      },
      {
        id: 'route_102k',
        routeNumber: '102K',
        operator: 'MTC',
        origin: 'Island Ground',
        originTamil: 'தீவு திடல்',
        destination: 'Kannagi Nagar',
        destinationTamil: 'கண்ணகி நகர்',
        stops: ['stop_island_ground', 'stop_kannagi_nagar'],
        polyline: [[13.0722, 80.28], [12.935, 80.23]],
        avgDurationMins: 45,
        fareRs: 18,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_102m',
        routeNumber: '102M',
        operator: 'MTC',
        origin: 'Adyar',
        originTamil: 'அடையாறு',
        destination: 'Manamathi',
        destinationTamil: 'மணமதி',
        stops: ['stop_adyar', 'stop_kelambakkam'],
        polyline: [[13.006, 80.257], [12.785, 80.222]],
        avgDurationMins: 60,
        fareRs: 24,
        frequencyMins: 20,
        type: 'ORDINARY'
      },
      {
        id: 'route_102p',
        routeNumber: '102P',
        operator: 'MTC',
        origin: 'Island Ground',
        originTamil: 'தீவு திடல்',
        destination: 'Perumbakkam',
        destinationTamil: 'பெரும்பாக்கம்',
        stops: ['stop_island_ground', 'stop_perumbakkam'],
        polyline: [[13.0722, 80.28], [12.895, 80.195]],
        avgDurationMins: 50,
        fareRs: 20,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_102s',
        routeNumber: '102S',
        operator: 'MTC',
        origin: 'Island Ground',
        originTamil: 'தீவு திடல்',
        destination: 'Okkiyam Thoraipakkam',
        destinationTamil: 'துரைப்பாக்கம்',
        stops: ['stop_island_ground', 'stop_siruseri'],
        polyline: [[13.0722, 80.28], [12.8285, 80.2185]],
        avgDurationMins: 45,
        fareRs: 18,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_102x',
        routeNumber: '102X',
        operator: 'MTC',
        origin: 'Island Ground',
        originTamil: 'தீவு திடல்',
        destination: 'Thiruporur',
        destinationTamil: 'திருப்போரூர்',
        stops: ['stop_island_ground', 'stop_thiruporur'],
        polyline: [[13.0722, 80.28], [12.7245, 80.1912]],
        avgDurationMins: 70,
        fareRs: 30,
        frequencyMins: 12,
        type: 'EXPRESS'
      },
      {
        id: 'route_104',
        routeNumber: '104',
        operator: 'MTC',
        origin: 'Redhills',
        originTamil: 'ரெட்ஹில்ஸ்',
        destination: 'Tambaram West',
        destinationTamil: 'தாம்பரம் மேற்கு',
        stops: ['stop_redhills', 'stop_tambaram_west'],
        polyline: [[13.198, 80.198], [12.925, 80.1171]],
        avgDurationMins: 75,
        fareRs: 30,
        frequencyMins: 15,
        type: 'EXPRESS'
      },
      {
        id: 'route_104a',
        routeNumber: '104A',
        operator: 'MTC',
        origin: 'Avadi',
        originTamil: 'ஆவடி',
        destination: 'Kilambakkam KCBT',
        destinationTamil: 'கிளம்பாக்கம்',
        stops: ['stop_avadi', 'stop_kilambakkam'],
        polyline: [[13.115, 80.1], [12.8342, 80.0768]],
        avgDurationMins: 75,
        fareRs: 32,
        frequencyMins: 12,
        type: 'EXPRESS'
      },
      {
        id: 'route_104c',
        routeNumber: '104C',
        operator: 'MTC',
        origin: 'Kilambakkam KCBT',
        originTamil: 'கிளம்பாக்கம்',
        destination: 'CMBT Koyambedu',
        destinationTamil: 'கோயம்பேடு',
        stops: ['stop_kilambakkam', 'stop_cmbt'],
        polyline: [[12.8342, 80.0768], [13.0694, 80.1948]],
        avgDurationMins: 65,
        fareRs: 28,
        frequencyMins: 10,
        type: 'EXPRESS'
      },
      {
        id: 'route_104cx',
        routeNumber: '104CX',
        operator: 'MTC',
        origin: 'Guduvanchery',
        originTamil: 'கூடுவாஞ்சேரி',
        destination: 'CMBT Koyambedu',
        destinationTamil: 'கோயம்பேடு',
        stops: ['stop_guduvanchery', 'stop_cmbt'],
        polyline: [[12.845, 80.065], [13.0694, 80.1948]],
        avgDurationMins: 60,
        fareRs: 26,
        frequencyMins: 12,
        type: 'EXPRESS'
      },
      {
        id: 'route_104f',
        routeNumber: '104F',
        operator: 'MTC',
        origin: 'Madhavaram',
        originTamil: 'மாதவரம்',
        destination: 'Kilambakkam KCBT',
        destinationTamil: 'கிளம்பாக்கம்',
        stops: ['stop_madhavaram', 'stop_kilambakkam'],
        polyline: [[13.145, 80.235], [12.8342, 80.0768]],
        avgDurationMins: 70,
        fareRs: 30,
        frequencyMins: 15,
        type: 'EXPRESS'
      },
      {
        id: 'route_104m',
        routeNumber: '104M',
        operator: 'MTC',
        origin: 'Madhavaram MMBT',
        originTamil: 'மாதவரம்',
        destination: 'Kilambakkam KCBT',
        destinationTamil: 'கிளம்பாக்கம்',
        stops: ['stop_madhavaram', 'stop_kilambakkam'],
        polyline: [[13.145, 80.235], [12.8342, 80.0768]],
        avgDurationMins: 70,
        fareRs: 30,
        frequencyMins: 15,
        type: 'EXPRESS'
      },
      {
        id: 'route_104t',
        routeNumber: '104T',
        operator: 'MTC',
        origin: 'Thiru.Vi.Ka. Nagar',
        originTamil: 'திரு.வி.க. நகர்',
        destination: 'Kilambakkam KCBT',
        destinationTamil: 'கிளம்பாக்கம்',
        stops: ['stop_thiruvika_nagar', 'stop_kilambakkam'],
        polyline: [[13.1154, 80.2356], [12.8342, 80.0768]],
        avgDurationMins: 65,
        fareRs: 28,
        frequencyMins: 15,
        type: 'EXPRESS'
      },
      {
        id: 'route_109',
        routeNumber: '109',
        operator: 'MTC',
        origin: 'Island Ground',
        originTamil: 'தீவு திடல்',
        destination: 'Kovalam',
        destinationTamil: 'கோவளம்',
        stops: ['stop_island_ground', 'stop_marina_beach', 'stop_kovalam'],
        polyline: [[13.0722, 80.28], [13.0398, 80.2782], [12.79, 80.25]],
        avgDurationMins: 60,
        fareRs: 24,
        frequencyMins: 12,
        type: 'ORDINARY'
      },
      {
        id: 'route_111',
        routeNumber: '111',
        operator: 'MTC',
        origin: 'Thiruverkadu',
        originTamil: 'திருவேற்காடு',
        destination: 'Tambaram West',
        destinationTamil: 'தாம்பரம் மேற்கு',
        stops: ['stop_thiruverkadu', 'stop_tambaram_west'],
        polyline: [[13.072, 80.122], [12.925, 80.1171]],
        avgDurationMins: 55,
        fareRs: 22,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_114',
        routeNumber: '114',
        operator: 'MTC',
        origin: 'Redhills',
        originTamil: 'ரெட்ஹில்ஸ்',
        destination: 'CMBT Koyambedu',
        destinationTamil: 'கோயம்பேடு',
        stops: ['stop_redhills', 'stop_cmbt'],
        polyline: [[13.198, 80.198], [13.0694, 80.1948]],
        avgDurationMins: 45,
        fareRs: 18,
        frequencyMins: 12,
        type: 'ORDINARY'
      },
      {
        id: 'route_118',
        routeNumber: '118',
        operator: 'MTC',
        origin: 'Tambaram West',
        originTamil: 'தாம்பரம் மேற்கு',
        destination: 'Maraimalai Nagar IE',
        destinationTamil: 'மறைமலை நகர்',
        stops: ['stop_tambaram_west', 'stop_maraimalai_nagar'],
        polyline: [[12.925, 80.1171], [12.795, 80.025]],
        avgDurationMins: 40,
        fareRs: 16,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_120',
        routeNumber: '120',
        operator: 'MTC',
        origin: 'Royapuram',
        originTamil: 'ராயபுரம்',
        destination: 'Avadi',
        destinationTamil: 'ஆவடி',
        stops: ['stop_royapuram', 'stop_avadi'],
        polyline: [[13.1112, 80.2925], [13.115, 80.1]],
        avgDurationMins: 50,
        fareRs: 20,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_121',
        routeNumber: '121',
        operator: 'MTC',
        origin: 'Minjur',
        originTamil: 'மீஞ்சூர்',
        destination: 'CMBT Koyambedu',
        destinationTamil: 'கோயம்பேடு',
        stops: ['stop_minjur', 'stop_cmbt'],
        polyline: [[13.28, 80.26], [13.0694, 80.1948]],
        avgDurationMins: 60,
        fareRs: 24,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_142',
        routeNumber: '142',
        operator: 'MTC',
        origin: 'Perambur',
        originTamil: 'பெரம்பூர்',
        destination: 'Vinayagapuram',
        destinationTamil: 'விநாயகபுரம்',
        stops: ['stop_perambur', 'stop_vinayagapuram'],
        polyline: [[13.1095, 80.2485], [13.135, 80.215]],
        avgDurationMins: 30,
        fareRs: 12,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_150',
        routeNumber: '150',
        operator: 'MTC',
        origin: 'Royapuram',
        originTamil: 'ராயபுரம்',
        destination: 'Avadi',
        destinationTamil: 'ஆவடி',
        stops: ['stop_royapuram', 'stop_avadi'],
        polyline: [[13.1112, 80.2925], [13.115, 80.1]],
        avgDurationMins: 50,
        fareRs: 20,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_153',
        routeNumber: '153',
        operator: 'MTC',
        origin: 'CMBT Koyambedu',
        originTamil: 'கோயம்பேடு',
        destination: 'Poonamallee',
        destinationTamil: 'பூவிருந்தவல்லி',
        stops: ['stop_cmbt', 'stop_poonamallee'],
        polyline: [[13.0694, 80.1948], [13.0485, 80.0912]],
        avgDurationMins: 40,
        fareRs: 16,
        frequencyMins: 10,
        type: 'ORDINARY'
      },
      {
        id: 'route_154',
        routeNumber: '154',
        operator: 'MTC',
        origin: 'T. Nagar',
        originTamil: 'தி. நகர்',
        destination: 'Poonamallee',
        destinationTamil: 'பூவிருந்தவல்லி',
        stops: ['stop_t_nagar_terminus', 'stop_guindy', 'stop_porur', 'stop_poonamallee'],
        polyline: [[13.0418, 80.2341], [13.0067, 80.202], [13.0335, 80.1582], [13.0485, 80.0912]],
        avgDurationMins: 45,
        fareRs: 18,
        frequencyMins: 12,
        type: 'ORDINARY'
      },
      {
        id: 'route_166',
        routeNumber: '166',
        operator: 'MTC',
        origin: 'Iyyappanthangal',
        originTamil: 'அய்யப்பன்தாங்கல்',
        destination: 'Tambaram West',
        destinationTamil: 'தாம்பரம் மேற்கு',
        stops: ['stop_iyyappanthangal', 'stop_tambaram_west'],
        polyline: [[13.0385, 80.1385], [12.925, 80.1171]],
        avgDurationMins: 40,
        fareRs: 18,
        frequencyMins: 12,
        type: 'ORDINARY'
      },
      {
        id: 'route_170c',
        routeNumber: '170C',
        operator: 'MTC',
        origin: 'Thiru.Vi.Ka. Nagar',
        originTamil: 'திரு.வி.க. நகர்',
        destination: 'Guindy TVK Estate',
        destinationTamil: 'கிண்டி',
        stops: ['stop_thiruvika_nagar', 'stop_guindy'],
        polyline: [[13.1154, 80.2356], [13.0067, 80.202]],
        avgDurationMins: 45,
        fareRs: 18,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_170tx',
        routeNumber: '170TX',
        operator: 'MTC',
        origin: 'K. Kannadasan Nagar',
        originTamil: 'க. கண்ணதாசன் நகர்',
        destination: 'Kilambakkam KCBT',
        destinationTamil: 'கிளம்பாக்கம்',
        stops: ['stop_kannadasan_nagar', 'stop_cmbt', 'stop_kilambakkam'],
        polyline: [[13.1345, 80.2465], [13.0694, 80.1948], [12.8342, 80.0768]],
        avgDurationMins: 75,
        fareRs: 32,
        frequencyMins: 15,
        type: 'EXPRESS'
      },
      {
        id: 'route_188c',
        routeNumber: '188C',
        operator: 'MTC',
        origin: 'Royapuram',
        originTamil: 'ராயபுரம்',
        destination: 'Kundrathur',
        destinationTamil: 'குன்றத்தூர்',
        stops: ['stop_royapuram', 'stop_ramapuram', 'stop_kundrathur'],
        polyline: [[13.1112, 80.2925], [13.0385, 80.1785], [12.9978, 80.0972]],
        avgDurationMins: 60,
        fareRs: 24,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_202',
        routeNumber: '202',
        operator: 'MTC',
        origin: 'Tambaram West',
        originTamil: 'தாம்பரம் மேற்கு',
        destination: 'Avadi',
        destinationTamil: 'ஆவடி',
        stops: ['stop_tambaram_west', 'stop_avadi'],
        polyline: [[12.925, 80.1171], [13.115, 80.1]],
        avgDurationMins: 50,
        fareRs: 20,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_206',
        routeNumber: '206',
        operator: 'MTC',
        origin: 'Kilambakkam KCBT',
        originTamil: 'கிளம்பாக்கம்',
        destination: 'Avadi',
        destinationTamil: 'ஆவடி',
        stops: ['stop_kilambakkam', 'stop_avadi'],
        polyline: [[12.8342, 80.0768], [13.115, 80.1]],
        avgDurationMins: 70,
        fareRs: 30,
        frequencyMins: 15,
        type: 'EXPRESS'
      },
      {
        id: 'route_221',
        routeNumber: '221',
        operator: 'MTC',
        origin: 'M.G.R. Central',
        originTamil: 'சென்ட்ரல்',
        destination: 'Thiruporur',
        destinationTamil: 'திருப்போரூர்',
        stops: ['stop_broadway', 'stop_thiruporur'],
        polyline: [[13.0878, 80.2835], [12.7245, 80.1912]],
        avgDurationMins: 75,
        fareRs: 32,
        frequencyMins: 12,
        type: 'EXPRESS'
      },
      {
        id: 'route_242',
        routeNumber: '242',
        operator: 'MTC',
        origin: 'Island Ground',
        originTamil: 'தீவு திடல்',
        destination: 'Redhills',
        destinationTamil: 'ரெட்ஹில்ஸ்',
        stops: ['stop_island_ground', 'stop_redhills'],
        polyline: [[13.0722, 80.28], [13.198, 80.198]],
        avgDurationMins: 55,
        fareRs: 22,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_266',
        routeNumber: '266',
        operator: 'MTC',
        origin: 'Avadi',
        originTamil: 'ஆவடி',
        destination: 'Tambaram West',
        destinationTamil: 'தாம்பரம் மேற்கு',
        stops: ['stop_avadi', 'stop_tambaram_west'],
        polyline: [[13.115, 80.1], [12.925, 80.1171]],
        avgDurationMins: 50,
        fareRs: 20,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_297',
        routeNumber: '297',
        operator: 'MTC',
        origin: 'Kilambakkam KCBT',
        originTamil: 'கிளம்பாக்கம்',
        destination: 'Thiruvallur',
        destinationTamil: 'திருவள்ளூர்',
        stops: ['stop_kilambakkam', 'stop_thiruvallur'],
        polyline: [[12.8342, 80.0768], [13.145, 79.91]],
        avgDurationMins: 85,
        fareRs: 36,
        frequencyMins: 15,
        type: 'EXPRESS'
      },
      {
        id: 'route_500',
        routeNumber: '500',
        operator: 'MTC',
        origin: 'Tambaram West',
        originTamil: 'தாம்பரம் மேற்கு',
        destination: 'Chengalpattu NT',
        destinationTamil: 'செங்கல்பட்டு',
        stops: ['stop_tambaram_west', 'stop_chengalpattu'],
        polyline: [[12.925, 80.1171], [12.682, 79.982]],
        avgDurationMins: 50,
        fareRs: 22,
        frequencyMins: 10,
        type: 'EXPRESS'
      },
      {
        id: 'route_570',
        routeNumber: '570',
        operator: 'MTC',
        origin: 'CMBT Koyambedu',
        originTamil: 'கோயம்பேடு',
        destination: 'Kelambakkam',
        destinationTamil: 'கேளம்பாக்கம்',
        stops: ['stop_cmbt', 'stop_vadapalani', 'stop_power_house', 'stop_ashok_pillar', 'stop_guindy', 'stop_siruseri'],
        polyline: [[13.0694, 80.1948], [13.05, 80.2121], [13.0482, 80.2175], [13.0352, 80.2123], [13.0067, 80.202], [12.8285, 80.2185]],
        avgDurationMins: 75,
        fareRs: 32,
        frequencyMins: 10,
        type: 'EXPRESS'
      },
      {
        id: 'route_578',
        routeNumber: '578',
        operator: 'MTC',
        origin: 'Poonamallee',
        originTamil: 'பூவிருந்தவல்லி',
        destination: 'Sunguvarchathiram',
        destinationTamil: 'சுங்குவாா்சத்திரம்',
        stops: ['stop_poonamallee', 'stop_sunguvarchathiram'],
        polyline: [[13.0485, 80.0912], [12.975, 79.88]],
        avgDurationMins: 45,
        fareRs: 20,
        frequencyMins: 15,
        type: 'ORDINARY'
      },
      {
        id: 'route_580',
        routeNumber: '580',
        operator: 'MTC',
        origin: 'Avadi',
        originTamil: 'ஆவடி',
        destination: 'Arani',
        destinationTamil: 'ஆரணி',
        stops: ['stop_avadi', 'stop_arani'],
        polyline: [[13.115, 80.1], [13.25, 80.09]],
        avgDurationMins: 60,
        fareRs: 24,
        frequencyMins: 20,
        type: 'ORDINARY'
      },
      {
        id: 'route_588',
        routeNumber: '588',
        operator: 'MTC',
        origin: 'Thiruvanmiyur',
        originTamil: 'திருவான்மியூர்',
        destination: 'Mamallapuram',
        destinationTamil: 'மாமல்லபுரம்',
        stops: ['stop_thiruvanmiyur', 'stop_mamallapuram'],
        polyline: [[12.983, 80.2594], [12.62, 80.19]],
        avgDurationMins: 65,
        fareRs: 28,
        frequencyMins: 15,
        type: 'DELUXE'
      },
      {
        id: 'route_591',
        routeNumber: '591',
        operator: 'MTC',
        origin: 'Poonamallee',
        originTamil: 'பூவிருந்தவல்லி',
        destination: 'Perambakkam',
        destinationTamil: 'பெரம்பாக்கம்',
        stops: ['stop_poonamallee', 'stop_perambakkam'],
        polyline: [[13.0485, 80.0912], [13.015, 79.9]],
        avgDurationMins: 50,
        fareRs: 22,
        frequencyMins: 20,
        type: 'ORDINARY'
      },
      {
        id: 'route_597',
        routeNumber: '597',
        operator: 'MTC',
        origin: 'T. Nagar',
        originTamil: 'தி. நகர்',
        destination: 'Thiruvallur',
        destinationTamil: 'திருவள்ளூர்',
        stops: ['stop_t_nagar_terminus', 'stop_thiruvallur'],
        polyline: [[13.0418, 80.2341], [13.145, 79.91]],
        avgDurationMins: 75,
        fareRs: 30,
        frequencyMins: 15,
        type: 'EXPRESS'
      },
      {
        id: 'route_m27',
        routeNumber: 'M27',
        operator: 'MTC',
        origin: 'CMBT Koyambedu',
        originTamil: 'கோயம்பேடு',
        destination: 'T. Nagar',
        destinationTamil: 'தி. நகர்',
        stops: ['stop_cmbt', 'stop_vadapalani', 'stop_t_nagar_terminus'],
        polyline: [[13.0694, 80.1948], [13.05, 80.2121], [13.0418, 80.2341]],
        avgDurationMins: 30,
        fareRs: 14,
        frequencyMins: 10,
        type: 'MINI'
      },
      {
        id: 'route_m88',
        routeNumber: 'M88',
        operator: 'MTC',
        origin: 'Kundrathur',
        originTamil: 'குன்றத்தூர்',
        destination: 'Vadapalani',
        destinationTamil: 'வடபழனி',
        stops: ['stop_kundrathur', 'stop_vadapalani'],
        polyline: [[12.9978, 80.0972], [13.05, 80.2121]],
        avgDurationMins: 35,
        fareRs: 15,
        frequencyMins: 10,
        type: 'MINI'
      },
      {
        id: 'route_s27',
        routeNumber: 'S27',
        operator: 'MTC',
        origin: 'Porur',
        originTamil: 'போரூர்',
        destination: 'Guindy TVK Estate',
        destinationTamil: 'கிண்டி',
        stops: ['stop_porur', 'stop_guindy'],
        polyline: [[13.0335, 80.1582], [13.0067, 80.202]],
        avgDurationMins: 25,
        fareRs: 12,
        frequencyMins: 15,
        type: 'MINI'
      }
    ];
  }

  private seedVehicles() {
    this.vehicles = [
      { id: 'TN-01-N-8812', busNumber: '88K', routeId: 'route_88k', operator: 'MTC', lat: 13.0335, lng: 80.1582, heading: 85, speedKmh: 32, previousStopId: 'stop_mangadu', currentStopId: 'stop_porur', nextStopId: 'stop_ramapuram', remainingStopsCount: 6, delayMins: 1, occupancy: 'MEDIUM', isLive: true, lastUpdated: new Date().toISOString() },
      { id: 'TN-01-N-2107', busNumber: '21G', routeId: 'route_21g', operator: 'MTC', lat: 13.0067, lng: 80.2020, heading: 180, speedKmh: 35, previousStopId: 'stop_island_ground', currentStopId: 'stop_guindy', nextStopId: 'stop_tambaram_west', remainingStopsCount: 2, delayMins: 0, occupancy: 'HIGH', isLive: true, lastUpdated: new Date().toISOString() },
      { id: 'TN-01-N-1107', busNumber: '11G', routeId: 'route_11g', operator: 'MTC', lat: 13.0482, lng: 80.2175, heading: 90, speedKmh: 30, previousStopId: 'stop_ashok_pillar', currentStopId: 'stop_power_house', nextStopId: 'stop_kodambakkam_rs', remainingStopsCount: 4, delayMins: 0, occupancy: 'LOW', isLive: true, lastUpdated: new Date().toISOString() },
      { id: 'TN-01-N-9842', busNumber: '570', routeId: 'route_570', operator: 'MTC', lat: 13.0482, lng: 80.2175, heading: 175, speedKmh: 34, previousStopId: 'stop_vadapalani', currentStopId: 'stop_power_house', nextStopId: 'stop_ashok_pillar', remainingStopsCount: 8, delayMins: 2, occupancy: 'MEDIUM', isLive: true, lastUpdated: new Date().toISOString() },
      { id: 'TN-01-N-4412', busNumber: '23C', routeId: 'route_23c', operator: 'MTC', lat: 13.0514, lng: 80.2245, heading: 310, speedKmh: 28, previousStopId: 'stop_t_nagar_terminus', currentStopId: 'stop_kodambakkam', nextStopId: 'stop_valluvar_kottam', remainingStopsCount: 1, delayMins: 0, occupancy: 'HIGH', isLive: true, lastUpdated: new Date().toISOString() },
      { id: 'TN-01-N-1901', busNumber: '19A', routeId: 'route_19a', operator: 'MTC', lat: 13.0418, lng: 80.2341, heading: 170, speedKmh: 38, previousStopId: 'stop_t_nagar_terminus', currentStopId: 'stop_t_nagar_terminus', nextStopId: 'stop_siruseri', remainingStopsCount: 1, delayMins: 0, occupancy: 'LOW', isLive: true, lastUpdated: new Date().toISOString() },
      { id: 'TN-01-N-0101', busNumber: '1', routeId: 'route_1', operator: 'MTC', lat: 13.0878, lng: 80.2835, heading: 190, speedKmh: 30, previousStopId: 'stop_broadway', currentStopId: 'stop_broadway', nextStopId: 'stop_island_ground', remainingStopsCount: 3, delayMins: 0, occupancy: 'MEDIUM', isLive: true, lastUpdated: new Date().toISOString() }
    ];
  }

  public getStops(): BusStop[] {
    return this.stops;
  }

  public getRoutes(): BusRoute[] {
    return this.routes;
  }

  public getVehicles(): VehiclePosition[] {
    return this.vehicles;
  }
}

export const dbStore = new DatabaseStore();
